### ISSUE TITLE
AWS server pending

### ISSUE THREAD

**Issue by hseok-oh** [tizendotnet/netcore-jenkins#20]
Myget packaging job pended since 2018.1.3 so I aborted it.
http://jenkins:8080/job/manage_myget/job/manage_tizen_nupkgs/3527

I found that 1600~ jobs queued because of this.

**Comment by hqueue** [comment]
@hseok-oh Thanks for the reporting and managing.

**Comment by hqueue** [comment]
BTW if look into below two jobs, it seems that CI is doing a same jobs.

http://jenkins:8080/job/manage_myget/job/manage_tizen_nupkgs/4228/console
http://jenkins:8080/job/manage_myget/job/manage_tizen_nupkgs/4229/console

And also new tasks are being queued less than an minutes.

@alpencolt @ragmani  Is this a expected behavior ?

**Comment by alpencolt** [comment]
Thank you for reporting.
@hqueue I think no. We will check.
cc @gbalykov
